// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Weathered.Models;

public partial class PastWeekDatum
{
    public int PastWeekDataId { get; set; }

    public int StationLocId { get; set; }

    public string TempData { get; set; }

    public string PrecipData { get; set; }

    public DateOnly? LastUpdated { get; set; }

    public virtual StationLoc StationLoc { get; set; }
}