// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Weathered.Models;

public partial class StationLoc
{
    public int StationLocId { get; set; }

    public string StationNumber { get; set; }

    public string Name { get; set; }

    public string Region { get; set; }

    public string Country { get; set; }

    public float Lat { get; set; }

    public float Lon { get; set; }

    public virtual PastWeekDatum PastWeekData { get; set; }
}