// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Weathered.Models;

public partial class WeatheredContext : DbContext
{
    public WeatheredContext(DbContextOptions<WeatheredContext> options)
        : base(options)
    {
    }

    public virtual DbSet<PastWeekDatum> PastWeekData { get; set; }

    public virtual DbSet<StationLoc> StationLocs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PastWeekDatum>(entity =>
        {
            entity.HasKey(e => e.PastWeekDataId).HasName("past_week_data_pkey");

            entity.ToTable("past_week_data");

            entity.Property(e => e.PastWeekDataId).HasColumnName("past_week_data_id");
            entity.Property(e => e.LastUpdated).HasColumnName("last_updated");
            entity.Property(e => e.PrecipData).HasColumnName("precip_data");
            entity.Property(e => e.StationLocId).HasColumnName("station_loc_id");
            entity.Property(e => e.TempData).HasColumnName("temp_data");

            entity.HasOne(d => d.StationLoc).WithOne(p => p.PastWeekData)
                .HasForeignKey<PastWeekDatum>(d => d.StationLocId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_station_locs");
        });

        modelBuilder.Entity<StationLoc>(entity =>
        {
            entity.HasKey(e => e.StationLocId).HasName("station_locs_pkey");

            entity.ToTable("station_locs");

            entity.Property(e => e.StationLocId).HasColumnName("station_loc_id");
            entity.Property(e => e.Country)
                .HasMaxLength(2)
                .HasColumnName("country");
            entity.Property(e => e.Lat).HasColumnName("lat");
            entity.Property(e => e.Lon).HasColumnName("lon");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Region)
                .HasMaxLength(5)
                .HasColumnName("region");
            entity.Property(e => e.StationNumber)
                .HasMaxLength(100)
                .HasColumnName("station_number");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}